basePath: /v1
definitions:
  routes.Article:
    properties:
      date:
        type: string
      id:
        type: string
      img:
        type: string
      name:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: admin@benweare.co.uk
    name: Benjamin Weare
  description: This is an edge collector variant of the benweare.co.uk-api written
    in GO
  title: benweare.co.uk-api
  version: "1.0"
paths:
  /news:
    get:
      description: get all articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Article'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show all articles
      tags:
      - News
  /news/{articleId}:
    get:
      description: get article by ID
      parameters:
      - description: Article ID
        in: path
        name: articleId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.Article'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Obtain a news article by ID
      tags:
      - News
swagger: "2.0"
